<?php
/** @var Match[] $matches */
use EduBet\Match\Entity\Match;

?>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Tijdstip</th>
        <th></th>
        <th>Thuis</th>
        <th>Uit</th>
        <th>Competitie</th>
        <th>WhoScored</th>
        <th colspan="3">Betfair Odds</th>
        <th colspan="4">PickForWin</th>
    </tr>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>1</th>
        <th>X</th>
        <th>2</th>
        <th>1</th>
        <th>X</th>
        <th>2</th>
        <th>Pick</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($matches as $match): ?>
        <tr class="<?php echo $this->fixtureRowClass($match); ?>" id="match-<?php echo $match->getId(); ?>">
            <th scope="row">
                <?php echo strftime("%a %e %b %R", $match->getTimestamp()); ?>
            </th>
            <td>
                <span class="<?php echo $this->flagClass($match); ?>"></span>
            </td>
            <td>
                <?php echo $match->getHomeTeam()->getName(); ?>
            </td>
            <td>
                <?php echo $match->getAwayTeam()->getName(); ?>
            </td>
            <td>
                <?php echo $match->getTournament()->getName(); ?>
            </td>
            <td>
                <?php
                    if (null != $match->getWhoScoredPreview()) {
                        echo $match->getWhoScoredPreview()->toString();
                    }
                ?>
            </td>
            <td>
                <?php
                    if (null != $match->getOdds()) {
                        echo $match->getOdds()->getHome();
                    }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getOdds()) {
                    echo $match->getOdds()->getDraw();
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getOdds()) {
                    echo $match->getOdds()->getAway();
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getHome()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getDraw()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getAway()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getPick();
                }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>