<?php
/** @var Match[] $matches */
use EduBet\Match\Entity\Match;

?>
<table id="fixtures-table" class="table table-striped">
    <thead>
    <tr>
        <th colspan="2">Tijdstip</th>
        <th></th>
        <th>Thuis</th>
        <th>Uit</th>
        <th>Strategy</th>
        <th>WhoScored</th>
        <th colspan="3">Betfair Odds</th>
        <th colspan="4">PickForWin</th>
    </tr>
    <tr>
        <th>Tijd</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>1</th>
        <th>X</th>
        <th>2</th>
        <th>1</th>
        <th>X</th>
        <th>2</th>
        <th>Pick</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($matches as $match): ?>
        <tr id="match-<?php echo $match->getId(); ?>">
            <th scope="row">
                <?php echo $match->getDutchDateTime()->format("Y-m-d H:i"); ?>
            </th>
            <th scope="row">
                <?php echo $match->getDutchDateTime()->format("D"); ?>
            </th>
            <td>
                <span class="<?php echo $this->flagClass($match); ?>"></span>
            </td>
            <td>
                <?php echo $match->getHomeTeam()->getName(); ?>
                <br />
                <span style="font-size:9px">
                    <?php echo $match->getHomeTeamForm()." (T:".$match->getHomeTeamHomeForm().")"; ?>
                </span>
            </td>
            <td>
                <?php echo $match->getAwayTeam()->getName(); ?>
                <br />
                <span style="font-size:9px">
                    <?php echo $match->getAwayTeamForm()." (U:".$match->getAwayTeamAwayForm().")"; ?>
                </span>
            </td>
            <td>
                <?php echo $this->strategyLabels($match); ?>
            </td>
            <td>
                <?php
                    if (null != $match->getWhoScoredPreview()) {
                        echo $match->getWhoScoredPreview()->toString();
                    }
                ?>
            </td>
            <td>
                <?php
                    if (null != $match->getOdds()) {
                        echo $match->getOdds()->getHome();
                    }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getOdds()) {
                    echo $match->getOdds()->getDraw();
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getOdds()) {
                    echo $match->getOdds()->getAway();
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getHome()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getDraw()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getAway()."%";
                }
                ?>
            </td>
            <td>
                <?php
                if (null != $match->getPickForWin()) {
                    echo $match->getPickForWin()->getPick();
                }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
        $('#fixtures-table').DataTable(
            {
                paging: false
            }
        );
    });
</script>