<?php
    /** @var \EduBet\Analysis\Entity\PredictionByWeek $predictionByWeek  */
?>

<div id="predictionByWeek"></div>

<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Year', <?php echo "'".implode("', '", $predictionByWeek->getSources())."'"; ?>],
            <?php foreach ($predictionByWeek->getWeeks() as $week): ?>
                <?php echo "['".$week."'"; ?>
                <?php foreach ($predictionByWeek->getSources() as $source): ?>
                    <?php echo ", ".$predictionByWeek->getPrediction($source, $week); ?>
                <?php endforeach; ?>
                <?php echo "],"; ?>
            <?php endforeach; ?>
        ]);

        var options = {
            title: 'Succes per week',
            curveType: 'function',
            legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('predictionByWeek'));

        chart.draw(data, options);
    }
</script>