<?php
use EduBet\Analysis\Entity\PredictionByWeek;
use EduBet\Analysis\Entity\ProfitByWeek;

/** @var PredictionByWeek $predictionByWeek  */
/** @var ProfitByWeek $profitByWeek */
?>
<div id="profitByWeek"></div>
<div id="predictionByWeek"></div>

<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Year', <?php echo "'".implode("', '", $predictionByWeek->getSources())."'"; ?>],
            <?php foreach ($predictionByWeek->getWeeks() as $week): ?>
                <?php echo "['".$week."'"; ?>
                <?php foreach ($predictionByWeek->getSources() as $source): ?>
                    <?php echo ", ".($predictionByWeek->getPrediction($source, $week) / 100); ?>
                <?php endforeach; ?>
                <?php echo "],"; ?>
            <?php endforeach; ?>
        ]);

        var options = {
            title: 'Succes per week',
            legend: { position: 'bottom' },
            vAxis: {format: 'percent'},
            height: 400
        };

        var chart = new google.visualization.LineChart(document.getElementById('predictionByWeek'));

        chart.draw(data, options);

        var profitData = google.visualization.arrayToDataTable([
            ['Year', <?php echo "'".implode("', '", $profitByWeek->getSources())."'"; ?>],
            <?php foreach ($profitByWeek->getWeeks() as $week): ?>
                <?php echo "['".$week."'"; ?>
                    <?php foreach ($profitByWeek->getSources() as $source): ?>
                        <?php
                            $value = $profitByWeek->getProfit($source, $week);
                            if (is_null($value)) {
                                $value = "null";
                            }
                            echo ", ".$value;
                        ?>
                    <?php endforeach; ?>
                <?php echo "],"; ?>
            <?php endforeach; ?>
        ]);

        var profitOptions = {
            title: 'Winst per week',
            legend: { position: 'bottom' },
            vAxis: {format: '\u20AC #'},
            height: 400
        };

        var profitChart = new google.visualization.LineChart(document.getElementById('profitByWeek'));

        profitChart.draw(profitData, profitOptions);
    }
</script>